remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Web Development Bootcamp Tasks
description: This site holds a list of task that I have completed under the web development bootcamp conducted by Gtech Mulearn.